name: Daily render ping

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: curl --fail --silent --show-error --max-time 30 -I https://mailharpoon-backend.onrender.com/
